/**
 * All LLM Models across the 6 requested families supporting:
 * - prompt
 * - system_prompt
 * - image_url (multimodal vision)
 *
 * Sourced directly from muapi_llm_models_reference.md
 */

export const AI_MODELS = [
  // --- 1. Abliterated / Low-Refusal / Uncensored LLMs ---
  {
    id: "mimo-v2-6-flash-abliterated",
    name: "MiMo V2.6 Flash Abliterated",
    group: "Abliterated / Uncensored",
    tag: "Vision & Fast",
    icon: "🔓",
  },
  {
    id: "abliterated-model",
    name: "Abliterated Model Base",
    group: "Abliterated / Uncensored",
    tag: "Vision & Uncensored",
    icon: "🔓",
  },
  {
    id: "qwen-3-8-27b-obliterated",
    name: "Qwen 3.8 27B Obliterated",
    group: "Abliterated / Uncensored",
    tag: "Vision & Reasoning",
    icon: "🔥",
  },
  {
    id: "qwen-3-8-27b-abliterated",
    name: "Qwen 3.8 27B Abliterated",
    group: "Abliterated / Uncensored",
    tag: "Vision & Low Refusal",
    icon: "🔥",
  },
  {
    id: "qwen-3-5-27b-queen-derestricted",
    name: "Qwen 3.5 27B Queen Derestricted",
    group: "Abliterated / Uncensored",
    tag: "Vision & 262k ctx",
    icon: "👑",
  },
  {
    id: "qwen-3-5-27b-blossom-derestricted",
    name: "Qwen 3.5 27B Blossom Derestricted",
    group: "Abliterated / Uncensored",
    tag: "Vision & 262k ctx",
    icon: "🌸",
  },
  {
    id: "qwen-3-5-27b-opus-distilled-derestricted",
    name: "Qwen 3.5 27B Opus-Distilled Derestricted",
    group: "Abliterated / Uncensored",
    tag: "Vision & 262k ctx",
    icon: "⚡",
  },
  {
    id: "glm-5-3-flash-abliterated",
    name: "GLM 5.3 Flash Abliterated",
    group: "Abliterated / Uncensored",
    tag: "Vision & Fast",
    icon: "⚡",
  },
  {
    id: "gemma-4-31b-gembrain-abliterated",
    name: "Gemma 4 31B Gembrain Abliterated",
    group: "Abliterated / Uncensored",
    tag: "Vision & Creative",
    icon: "💎",
  },
  {
    id: "gemma-4-31b-sdft-abliterated",
    name: "Gemma 4 31B SDFT Abliterated",
    group: "Abliterated / Uncensored",
    tag: "Vision & 262k ctx",
    icon: "💎",
  },
  {
    id: "qwen-3-8-27b-queen",
    name: "Qwen 3.8 27B Queen",
    group: "Abliterated / Uncensored",
    tag: "Vision & 524k ctx",
    icon: "👑",
  },
  {
    id: "qwen-3-8-27b-fable",
    name: "Qwen 3.8 27B Fable",
    group: "Abliterated / Uncensored",
    tag: "Vision & Storytelling",
    icon: "📖",
  },

  // --- 2. OpenAI GPT Family ---
  {
    id: "gpt-5-nano",
    name: "GPT-5 Nano",
    group: "OpenAI GPT Family",
    tag: "High-Speed Vision",
    icon: "⚡",
  },
  {
    id: "gpt-5-2",
    name: "GPT-5.2",
    group: "OpenAI GPT Family",
    tag: "General Purpose",
    icon: "✨",
  },
  {
    id: "gpt-5-5",
    name: "GPT-5.5",
    group: "OpenAI GPT Family",
    tag: "Advanced Reasoning",
    icon: "🧠",
  },
  {
    id: "gpt-5-6-luna",
    name: "GPT-5.6 Luna",
    group: "OpenAI GPT Family",
    tag: "High-Efficiency",
    icon: "🌙",
  },
  {
    id: "gpt-5-6-terra",
    name: "GPT-5.6 Terra",
    group: "OpenAI GPT Family",
    tag: "Balanced",
    icon: "🌍",
  },
  {
    id: "gpt-5-6-sol",
    name: "GPT-5.6 Sol",
    group: "OpenAI GPT Family",
    tag: "Flagship",
    icon: "☀️",
  },
  {
    id: "gpt-6-astra",
    name: "GPT-6 Astra",
    group: "OpenAI GPT Family",
    tag: "Frontier Reasoning",
    icon: "🧠",
  },
  {
    id: "gpt-6-1-sol",
    name: "GPT-6.1 Sol Light",
    group: "OpenAI GPT Family",
    tag: "Fast & Capable",
    icon: "⚡",
  },

  // --- 3. Anthropic Claude Family ---
  {
    id: "claude-haiku-4-5",
    name: "Claude Haiku 4.5",
    group: "Anthropic Claude Family",
    tag: "Fast Vision",
    icon: "⚡",
  },
  {
    id: "claude-sonnet-4-5",
    name: "Claude Sonnet 4.5",
    group: "Anthropic Claude Family",
    tag: "Balanced",
    icon: "🎭",
  },
  {
    id: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    group: "Anthropic Claude Family",
    tag: "Coding & Vision",
    icon: "💻",
  },
  {
    id: "claude-sonnet-5",
    name: "Claude Sonnet 5",
    group: "Anthropic Claude Family",
    tag: "Flagship",
    icon: "⭐",
  },
  {
    id: "claude-sonnet-5-5",
    name: "Claude Sonnet 5.5",
    group: "Anthropic Claude Family",
    tag: "High-Capacity",
    icon: "🌟",
  },
  {
    id: "claude-opus-4-5",
    name: "Claude Opus 4.5",
    group: "Anthropic Claude Family",
    tag: "Reasoning",
    icon: "🔮",
  },
  {
    id: "claude-opus-4-6",
    name: "Claude Opus 4.6",
    group: "Anthropic Claude Family",
    tag: "Deep Thinker",
    icon: "🔮",
  },
  {
    id: "claude-opus-4-7",
    name: "Claude Opus 4.7",
    group: "Anthropic Claude Family",
    tag: "Multi-Modal",
    icon: "🔮",
  },
  {
    id: "claude-opus-4-8",
    name: "Claude Opus 4.8",
    group: "Anthropic Claude Family",
    tag: "Long Context",
    icon: "🔮",
  },
  {
    id: "claude-opus-5",
    name: "Claude Opus 5",
    group: "Anthropic Claude Family",
    tag: "Premier",
    icon: "👑",
  },
  {
    id: "claude-opus-5-5",
    name: "Claude Opus 5.5",
    group: "Anthropic Claude Family",
    tag: "Next-Gen",
    icon: "👑",
  },
  {
    id: "claude-fable-5",
    name: "Claude Fable 5",
    group: "Anthropic Claude Family",
    tag: "Creative Writing",
    icon: "📖",
  },
  {
    id: "claude-fable-5-1",
    name: "Claude Fable 5.1",
    group: "Anthropic Claude Family",
    tag: "Long Storytelling",
    icon: "📖",
  },

  // --- 4. Google Gemini Family ---
  {
    id: "gemini-2-5-flash",
    name: "Gemini 2.5 Flash",
    group: "Google Gemini Family",
    tag: "Ultra-Fast",
    icon: "⚡",
  },
  {
    id: "gemini-2-5-pro",
    name: "Gemini 2.5 Pro",
    group: "Google Gemini Family",
    tag: "Multimodal Pro",
    icon: "💠",
  },
  {
    id: "gemini-3-flash",
    name: "Gemini 3 Flash",
    group: "Google Gemini Family",
    tag: "Low-Latency",
    icon: "⚡",
  },
  {
    id: "gemini-3-pro",
    name: "Gemini 3 Pro",
    group: "Google Gemini Family",
    tag: "Deep Analysis",
    icon: "💠",
  },
  {
    id: "gemini-3-1-pro",
    name: "Gemini 3.1 Pro",
    group: "Google Gemini Family",
    tag: "MoE Flagship",
    icon: "💠",
  },
  {
    id: "gemini-3-5-flash",
    name: "Gemini 3.5 Flash",
    group: "Google Gemini Family",
    tag: "High Speed",
    icon: "⚡",
  },
  {
    id: "gemini-3-5-flash-openai",
    name: "Gemini 3.5 Flash (OpenAI)",
    group: "Google Gemini Family",
    tag: "OpenAI Format",
    icon: "⚡",
  },
  {
    id: "gemini-3-6-flash",
    name: "Gemini 3.6 Flash",
    group: "Google Gemini Family",
    tag: "Fast Vision",
    icon: "⚡",
  },
  {
    id: "gemini-3-6-flash-openai",
    name: "Gemini 3.6 Flash (OpenAI)",
    group: "Google Gemini Family",
    tag: "OpenAI Format",
    icon: "⚡",
  },
  {
    id: "gemini-3-7-flash",
    name: "Gemini 3.7 Flash",
    group: "Google Gemini Family",
    tag: "Hybrid Reasoner",
    icon: "🧠",
  },
  {
    id: "gemini-3-7-flash-openai",
    name: "Gemini 3.7 Flash (OpenAI)",
    group: "Google Gemini Family",
    tag: "OpenAI Format",
    icon: "🧠",
  },
  {
    id: "gemini-3-8-flash",
    name: "Gemini 3.8 Flash",
    group: "Google Gemini Family",
    tag: "Advanced Vision",
    icon: "⚡",
  },

  // --- 5. xAI Grok Family ---
  {
    id: "grok-4-3",
    name: "Grok 4.3",
    group: "xAI Grok Family",
    tag: "Conversational",
    icon: "🚀",
  },
  {
    id: "grok-4-5",
    name: "Grok 4.5",
    group: "xAI Grok Family",
    tag: "Real-Time Vision",
    icon: "🚀",
  },
  {
    id: "grok-4-6",
    name: "Grok 4.6",
    group: "xAI Grok Family",
    tag: "Coding & Logic",
    icon: "🚀",
  },
  {
    id: "grok-4-7",
    name: "Grok 4.7",
    group: "xAI Grok Family",
    tag: "Flagship Multimodal",
    icon: "🚀",
  },

  // --- 6. Moonshot Kimi & DeepSeek Family ---
  {
    id: "kimi-k3",
    name: "Moonshot Kimi K3",
    group: "Moonshot Kimi & DeepSeek",
    tag: "2.8T MoE / 1M ctx",
    icon: "🌙",
  },
  {
    id: "deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    group: "Moonshot Kimi & DeepSeek",
    tag: "Fast Vision",
    icon: "🐋",
  },
  {
    id: "deepseek-v4-1-flash",
    name: "DeepSeek V4.1 Flash",
    group: "Moonshot Kimi & DeepSeek",
    tag: "Reasoning Vision",
    icon: "🐋",
  },
  {
    id: "deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    group: "Moonshot Kimi & DeepSeek",
    tag: "Pro Reasoning",
    icon: "🐋",
  },
];

export const DEFAULT_MODEL = "gpt-6-1-sol";
